version: "3"

services:
  proxy:
    image: traefik
    ports:
      - "80:80"
      - "8100:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/.htpasswd:/etc/traefik/.htpasswd

networks:
  default:
    external:
      name: imixs_cloud_nw
