version: '3'

services:
 app:
   image: registry:2
   environment:
     REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.cert 
     REGISTRY_HTTP_TLS_KEY: /certs/domain.key
   volumes:
     - ~/registry/certs:/certs   
   ports:
     - 5000:5000
   networks:
     - net
   deploy:
     placement:
       constraints:
         - node.role == manager
networks:
   net:
     driver: overlay